### ISSUE TITLE
Error | The installation encountered an error while starting up.

### ISSUE THREAD

**Issue by JMElam** [MomoPZ/brackets-ckeditor#1]
Is anybody else having trouble installing this extension ? I keep getting an error message while trying to install.

**Comment by MomoPZ** [comment]
You get the error message because the extension depends on ckeditor. Just ignore the error and resume the installation with the second step:
2. Download [CKeditor](http://ckeditor.com/download) and extract it into the `brackets-ckeditor`-folder (don't rename folder containing CKEditor, name must remain `ckeditor`)

Maybe I should include ckeditor in the extension. But I don't know if this causes trouble with the software-licenses since I I'm not the creator of CKEditor. Secondly this means I always have to upgrade my extension to the latest version of ckeditor...
